### ISSUE TITLE
Set up present page

### ISSUE THREAD

**Issue by Frenchtoast0** [Frenchtoast0/Bible-Verse-Displayer#4]
The present.html will be for a secondary display (projector or otherwise).  It should have a centered box for displaying the verse text, a box at the bottom right for displaying the verse reference, and an image that covers the background (hardcoded for now, will be changeable through settings in the future).

**Comment by bloodmonk7** [comment]
Can i help you?

**Comment by Frenchtoast0** [comment]
Yes, you can

**Comment by Frenchtoast0** [comment]
Sorry,  I might actually work on this one.

**Comment by Frenchtoast0** [comment]
Part 1 added: https://github.com/Frenchtoast0/Bible-Verse-Displayer/pull/8

**Comment by Frenchtoast0** [comment]
Part 2: https://github.com/Frenchtoast0/Bible-Verse-Displayer/pull/9
